version: '3.3'
services:
  bambu-board:
    build: .
    ports:
      - '8080:8080'
      - '3000:3000'
    environment:
      - BambuBoardAPIPort=3000
      - BAMBUBOARD_HTTP_PORT=8080
      - BAMBUBOARD_PRINTER_URL=[Printer IP]
      - BAMBUBOARD_PRINTER_PORT=8883
      - BAMBUBOARD_PRINTER_SN=[YOUR_SN]
      - BAMBUBOARD_PRINTER_ACCESS_CODE=[YOUR_ACCESS_CODE]
      - BAMBUBOARD_BAMBU_USERNAME=[YOUR_BAMBU_USERNAME]
      - BAMBUBOARD_BAMBU_PASSWORD=[YOUR_BAMBU_PASSWORD]
      - BAMBUBOARD_USE_FARENHEIT=false
      - BAMBUBOARD_USE_12HOUR_FORMAT=false
    container_name: server